# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

SImputeZ_bin_c <- function(pBigMat, bin_index, typed_index, typed_value, lambda = 0.0, maf = 0.01, verbose = TRUE, threads = 0L) {
    .Call(`_SumTool_SImputeZ_bin_c`, pBigMat, bin_index, typed_index, typed_value, lambda, maf, verbose, threads)
}

SImputeZ_ld_bin_c <- function(pBigMat, pBigMat_G, bin_index, typed_index, typed_bin_index, typed_value, lambda = 0.0, maf = 0.01, verbose = TRUE, threads = 0L) {
    .Call(`_SumTool_SImputeZ_ld_bin_c`, pBigMat, pBigMat_G, bin_index, typed_index, typed_bin_index, typed_value, lambda, maf, verbose, threads)
}

rBed_c <- function(bfile, pBigMat, maxLine, add = TRUE, impt = TRUE, verbose = TRUE, threads = 0L) {
    invisible(.Call(`_SumTool_rBed_c`, bfile, pBigMat, maxLine, add, impt, verbose, threads))
}

wBed_c <- function(pBigMat, bed_file, threads = 0L, verbose = TRUE) {
    invisible(.Call(`_SumTool_wBed_c`, pBigMat, bed_file, threads, verbose))
}

#' Column number count
#'
#' To count number of column of a file
#'
#' @param filename, name of a file.
#' @examples
#' # reading data
#' bim_path <- system.file("extdata", "ref_geno.bim", package = "SumTool")
#' n <- FileNcol(bim_path)
#' @export
FileNcol <- function(filename) {
    .Call(`_SumTool_FileNcol`, filename)
}

#' Row number count
#'
#' To count number of row of a file
#'
#' @param filename, name of a file.
#' @examples
#' # reading data
#' bim_path <- system.file("extdata", "ref_geno.bim", package = "SumTool")
#' n <- FileNrow(bim_path)
#' @export
FileNrow <- function(filename) {
    .Call(`_SumTool_FileNrow`, filename)
}

VCF_Row_Col <- function(vcf_file) {
    .Call(`_SumTool_VCF_Row_Col`, vcf_file)
}

rMap_c <- function(map_file, out = NULL) {
    .Call(`_SumTool_rMap_c`, map_file, out)
}

rVCF_c <- function(vcf_file, pBigMat, maxLine, out, impt = TRUE, add = TRUE, verbose = TRUE, threads = 0L) {
    .Call(`_SumTool_rVCF_c`, vcf_file, pBigMat, maxLine, out, impt, add, verbose, threads)
}

SImpute_LD_bigm_c <- function(genomat, ldbigmat, index = NULL, chisq = 0L, lambda = 0, haps = FALSE, threads = 0L, verbose = TRUE) {
    invisible(.Call(`_SumTool_SImpute_LD_bigm_c`, genomat, ldbigmat, index, chisq, lambda, haps, threads, verbose))
}

SImpute_LD_norm_c <- function(pBigMat, index = NULL, chisq = 0L, lambda = 0, haps = FALSE, threads = 0L, verbose = TRUE) {
    .Call(`_SumTool_SImpute_LD_norm_c`, pBigMat, index, chisq, lambda, haps, threads, verbose)
}

LDprune_c <- function(pBigMat, index, r2_cutoff = 0.2, threads = 0L, verbose = TRUE) {
    .Call(`_SumTool_LDprune_c`, pBigMat, index, r2_cutoff, threads, verbose)
}

LDclump_c <- function(pBigMat, index, r2_cutoff, p, threads = 0L, verbose = TRUE) {
    .Call(`_SumTool_LDclump_c`, pBigMat, index, r2_cutoff, p, threads, verbose)
}

ldreg_h2 <- function(z2, ld, wld, M, N, maxz2 = 30, nblock = 200L, rep = 3L) {
    .Call(`_SumTool_ldreg_h2`, z2, ld, wld, M, N, maxz2, nblock, rep)
}

ldreg_rg <- function(z_t1, z_t2, ld, wld, M, N1, N2, nblock = 200L) {
    .Call(`_SumTool_ldreg_rg`, z_t1, z_t2, ld, wld, M, N1, N2, nblock)
}

LDscore_c <- function(pBigMat, index, r2 = TRUE, adjust = FALSE, threads = 0L, verbose = TRUE) {
    .Call(`_SumTool_LDscore_c`, pBigMat, index, r2, adjust, threads, verbose)
}

getCol <- function(pBigMat, col) {
    .Call(`_SumTool_getCol`, pBigMat, col)
}

glm_c <- function(y, X, indx, pBigMat, verbose = TRUE, threads = 0L) {
    .Call(`_SumTool_glm_c`, y, X, indx, pBigMat, verbose, threads)
}

sblup_bin <- function(pBigMat, n_gwas, typed_index, typed_value, lambda, verbose = TRUE, threads = 0L) {
    .Call(`_SumTool_sblup_bin`, pBigMat, n_gwas, typed_index, typed_value, lambda, verbose, threads)
}

hasNA <- function(pBigMat, threads = 0L) {
    .Call(`_SumTool_hasNA`, pBigMat, threads)
}

freq_snp <- function(pBigMat, index_, threads = 0L) {
    .Call(`_SumTool_freq_snp`, pBigMat, index_, threads)
}

freq_hap <- function(pBigMat, indx_1, indx_2) {
    .Call(`_SumTool_freq_hap`, pBigMat, indx_1, indx_2)
}

freq_s <- function(pBigMat, index_, threads = 0L) {
    .Call(`_SumTool_freq_s`, pBigMat, index_, threads)
}

freq_h <- function(pBigMat, indx_1, indx_2) {
    .Call(`_SumTool_freq_h`, pBigMat, indx_1, indx_2)
}

BigStat <- function(pBigMat, index_, threads = 0L) {
    .Call(`_SumTool_BigStat`, pBigMat, index_, threads)
}

which_c <- function(x, value, c = 1L) {
    .Call(`_SumTool_which_c`, x, value, c)
}

