# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

rData_c <- function(bfile, pBigMat, maxLine, impt = TRUE, verbose = TRUE, threads = 0L) {
    invisible(.Call(`_SumTool_rData_c`, bfile, pBigMat, maxLine, impt, verbose, threads))
}

wData_c <- function(pBigMat, bed_file, threads = 0L, verbose = TRUE) {
    invisible(.Call(`_SumTool_wData_c`, pBigMat, bed_file, threads, verbose))
}

#' Column number count
#'
#' To count number of column of a file
#'
#' @param filename, name of a file.
#' @examples
#' # reading data
#' bim_path <- system.file("extdata", "ref_geno.bim", package = "SumTool")
#' n <- FileNcol(bim_path)
FileNcol <- function(filename) {
    .Call(`_SumTool_FileNcol`, filename)
}

#' Row number count
#'
#' To count number of row of a file
#'
#' @param filename, name of a file.
#' @examples
#' # reading data
#' bim_path <- system.file("extdata", "ref_geno.bim", package = "SumTool")
#' n <- FileNrow(bim_path)
FileNrow <- function(filename) {
    .Call(`_SumTool_FileNrow`, filename)
}

rMap_c <- function(map_file, out = NULL) {
    .Call(`_SumTool_rMap_c`, map_file, out)
}

SImpute_LD_bigm_c <- function(genomat, ldbigmat, index = NULL, chisq = 0L, lambda = 0, haps = FALSE, threads = 0L, verbose = TRUE) {
    invisible(.Call(`_SumTool_SImpute_LD_bigm_c`, genomat, ldbigmat, index, chisq, lambda, haps, threads, verbose))
}

SImpute_LD_norm_c <- function(pBigMat, index = NULL, chisq = 0L, lambda = 0, haps = FALSE, threads = 0L, verbose = TRUE) {
    .Call(`_SumTool_SImpute_LD_norm_c`, pBigMat, index, chisq, lambda, haps, threads, verbose)
}

SImpute_LD_sparse_c <- function(pBigMat, index = NULL, chisq = 0L, lambda = 0, haps = FALSE, threads = 0L, verbose = TRUE) {
    .Call(`_SumTool_SImpute_LD_sparse_c`, pBigMat, index, chisq, lambda, haps, threads, verbose)
}

LDprune_c <- function(pBigMat, index, r2_cutoff = 0.2, threads = 0L, verbose = TRUE) {
    .Call(`_SumTool_LDprune_c`, pBigMat, index, r2_cutoff, threads, verbose)
}

LDclump_c <- function(pBigMat, index, r2_cutoff, p, threads = 0L, verbose = TRUE) {
    .Call(`_SumTool_LDclump_c`, pBigMat, index, r2_cutoff, p, threads, verbose)
}

ldreg_h2 <- function(z2, ld, wld, M, N, maxz2 = 30, nblock = 200L, rep = 3L) {
    .Call(`_SumTool_ldreg_h2`, z2, ld, wld, M, N, maxz2, nblock, rep)
}

ldreg_rg <- function(z_t1, z_t2, ld, wld, M, N1, N2, nblock = 200L) {
    .Call(`_SumTool_ldreg_rg`, z_t1, z_t2, ld, wld, M, N1, N2, nblock)
}

LDscore_c <- function(pBigMat, index, r2 = TRUE, adjust = FALSE, threads = 0L, verbose = TRUE) {
    .Call(`_SumTool_LDscore_c`, pBigMat, index, r2, adjust, threads, verbose)
}

sblup_bin <- function(pBigMat, n_gwas, typed_index, typed_value, lambda, verbose = TRUE, threads = 0L) {
    .Call(`_SumTool_sblup_bin`, pBigMat, n_gwas, typed_index, typed_value, lambda, verbose, threads)
}

SImputeZ_bin_c <- function(pBigMat, typed_index, typed_value, lambda = 0.0, maf = 0.01, haps = FALSE, verbose = TRUE, threads = 0L) {
    .Call(`_SumTool_SImputeZ_bin_c`, pBigMat, typed_index, typed_value, lambda, maf, haps, verbose, threads)
}

SImputeZ_ld_bin_c <- function(pBigMat, pBigMat_G, typed_index, typed_value, lambda = 0.0, maf = 0.01, haps = FALSE, verbose = TRUE, threads = 0L) {
    .Call(`_SumTool_SImputeZ_ld_bin_c`, pBigMat, pBigMat_G, typed_index, typed_value, lambda, maf, haps, verbose, threads)
}

SImpute_joint_c <- function(pBigMat, typed_index, typed_value, maf = 0.01, verbose = TRUE, threads = 0L) {
    .Call(`_SumTool_SImpute_joint_c`, pBigMat, typed_index, typed_value, maf, verbose, threads)
}

hasNA <- function(pBigMat, threads = 0L) {
    .Call(`_SumTool_hasNA`, pBigMat, threads)
}

freq_hap <- function(pBigMat, index_, threads = 0L) {
    .Call(`_SumTool_freq_hap`, pBigMat, index_, threads)
}

freq <- function(pBigMat, index_, threads = 0L) {
    .Call(`_SumTool_freq`, pBigMat, index_, threads)
}

BigStat <- function(pBigMat, index_, threads = 0L) {
    .Call(`_SumTool_BigStat`, pBigMat, index_, threads)
}

which_c <- function(x, value, c = 1L) {
    .Call(`_SumTool_which_c`, x, value, c)
}

